### ISSUE TITLE
Action

### ISSUE THREAD

**Issue by AhmedThahir** [robjhyndman/weird#2]
Dear Prof. Hyndman

Could you share the action that is used to create https://otexts.com/weird, so that I can self-host using GitHub pages?

**Comment by robjhyndman** [comment]
I do not host OTexts.com on Github Pages. However, I do host another quarto website on Github Pages. You can see the Github Action here: https://github.com/hprtc/website/blob/main/.github/workflows/quarto-publish-example.yml

**Comment by AhmedThahir** [comment]
I get the following error:

```
From https://github.com/AhmedThahir/weird
 * branch            gh-pages   -> FETCH_HEAD
 * [new branch]      gh-pages   -> origin/gh-pages
Rendering for publish:


[ 1/18] index.qmd
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'renv/activate.R': No such file or directory
Execution halted
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'renv/activate.R': No such file or directory
Execution halted
Problem with running R found at /usr/local/bin/Rscript to check environment configurations.
Please check your installation of R.

ERROR: Error
    at renderFiles (file:///opt/quarto/bin/quarto.js:78081:29)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async renderProject (file:///opt/quarto/bin/quarto.js:78479:25)
    at async renderForPublish (file:///opt/quarto/bin/quarto.js:109339:33)
    at async renderForPublish (file:///opt/quarto/bin/quarto.js:104866:24)
    at async Object.publish1 [as publish] (file:///opt/quarto/bin/quarto.js:105351:26)
    at async publishSite (file:///opt/quarto/bin/quarto.js:109376:38)
    at async publish7 (file:///opt/quarto/bin/quarto.js:109595:61)
    at async doPublish (file:///opt/quarto/bin/quarto.js:109555:13)
    at async publishAction (file:///opt/quarto/bin/quarto.js:109566:9)
Error: Process completed with exit code 1.
```

- Link to the action file: https://github.com/AhmedThahir/weird/actions/runs/11479338494/workflow
- Link to the action run: https://github.com/AhmedThahir/weird/actions/runs/11479338494/job/31945415772

**Comment by robjhyndman** [comment]
I'm not debugging your github action for you

**Comment by AhmedThahir** [comment]
Hi Prof, 
I believe there has be a miscommunication.

As I mentioned, I just want the following:

> Could you kindly share any resources that you used when you deployed the hprtc website? I will refer to them and resolve this myself.

**Comment by robjhyndman** [comment]
I have. Everything you need is on the hprtc website repo.
